from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from HJProtocol.NavStatus import NavStatus

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class NAV(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> NAV: ...
  @classmethod
  def GetRootAsNAV(cls, buf: bytes, offset: int) -> NAV: ...
  @classmethod
  def NAVBufferHasIdentifier(cls, buf: bytes, offset: int, size_prefixed: bool) -> bool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def NavStatus(self) -> typing.Literal[NavStatus.UNKNOWN, NavStatus.UNALIGNED, NavStatus.COARSE_ALIGN, NavStatus.FINE_ALIGN, NavStatus.ALIGNED]: ...
  def NavRoll(self) -> float: ...
  def NavPitch(self) -> float: ...
  def NavYaw(self) -> float: ...
  def NavLat(self) -> float: ...
  def NavLon(self) -> float: ...
  def NavAlt(self) -> float: ...
  def NavQua0(self) -> float: ...
  def NavQua1(self) -> float: ...
  def NavQua2(self) -> float: ...
  def NavQua3(self) -> float: ...
def NAVStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def NAVAddNavStatus(builder: flatbuffers.Builder, navStatus: typing.Literal[NavStatus.UNKNOWN, NavStatus.UNALIGNED, NavStatus.COARSE_ALIGN, NavStatus.FINE_ALIGN, NavStatus.ALIGNED]) -> None: ...
def NAVAddNavRoll(builder: flatbuffers.Builder, navRoll: float) -> None: ...
def NAVAddNavPitch(builder: flatbuffers.Builder, navPitch: float) -> None: ...
def NAVAddNavYaw(builder: flatbuffers.Builder, navYaw: float) -> None: ...
def NAVAddNavLat(builder: flatbuffers.Builder, navLat: float) -> None: ...
def NAVAddNavLon(builder: flatbuffers.Builder, navLon: float) -> None: ...
def NAVAddNavAlt(builder: flatbuffers.Builder, navAlt: float) -> None: ...
def NAVAddNavQua0(builder: flatbuffers.Builder, navQua0: float) -> None: ...
def NAVAddNavQua1(builder: flatbuffers.Builder, navQua1: float) -> None: ...
def NAVAddNavQua2(builder: flatbuffers.Builder, navQua2: float) -> None: ...
def NAVAddNavQua3(builder: flatbuffers.Builder, navQua3: float) -> None: ...
def NAVEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

