# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HJProtocol

# 항법 정렬 상태 (Navigation Status)
class NavStatus(object):
    UNKNOWN = 0
    UNALIGNED = 1
    COARSE_ALIGN = 2
    FINE_ALIGN = 3
    ALIGNED = 4
