# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HJProtocol

# 운용 모드 (Operation Mode)
class OperationMode(object):
    UNKNOWN = 0
    INIT = 1
    IDLE = 2
    DIAG = 3
    ARMED = 4
    FLIGHT = 5
    KILL = 6
    RECOVERY = 7
