# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HJProtocol

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Telecommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Telecommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelecommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TelecommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x4A\x54\x43", size_prefixed=size_prefixed)

    # Telecommand
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Telecommand
    def CmdMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Telecommand
    def CmdConfig(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Telecommand
    def CmdNav(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TelecommandStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    TelecommandStart(builder)

def TelecommandAddCmdMode(builder: flatbuffers.Builder, cmdMode: int):
    builder.PrependInt8Slot(0, cmdMode, 0)

def AddCmdMode(builder: flatbuffers.Builder, cmdMode: int):
    TelecommandAddCmdMode(builder, cmdMode)

def TelecommandAddCmdConfig(builder: flatbuffers.Builder, cmdConfig: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cmdConfig), 0)

def AddCmdConfig(builder: flatbuffers.Builder, cmdConfig: int):
    TelecommandAddCmdConfig(builder, cmdConfig)

def TelecommandAddCmdNav(builder: flatbuffers.Builder, cmdNav: bool):
    builder.PrependBoolSlot(2, cmdNav, 0)

def AddCmdNav(builder: flatbuffers.Builder, cmdNav: bool):
    TelecommandAddCmdNav(builder, cmdNav)

def TelecommandEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TelecommandEnd(builder)
